# kairOS build configuration
#
# SPDX-License-Identifier: Apache-2.0

base:
  amd64:
    url: "https://releases.ubuntu.com/resolute/ubuntu-26.04.1-desktop-amd64.iso"
    sha256: ""

  arm64:
    url: "https://cdimage.ubuntu.com/releases/resolute/release/ubuntu-26.04.1-desktop-arm64.iso"
    sha256: ""

apps:
  ollama:
    url: "https://ollama.com/install.sh"
    sha256: ""

  opencode:
    url: "https://opencode.ai/install"
    sha256: ""

  openchamber:
    url: "https://api.github.com/repos/openchamber/openchamber/releases/latest"
    sha256: ""
